######################################################################
# Automatically generated by qmake (3.1) Fri May 17 11:24:46 2019
######################################################################

TEMPLATE = app
QT += widgets
TARGET = miv
INCLUDEPATH += ../src
LIBS += -lopencv_imgproc -lopencv_imgcodecs -lopencv_core

DEFINES += QT_DEPRECATED_WARNINGS


# Input
HEADERS += ImageVault.h Image.h Viewer.h Navigator.h
SOURCES += ImageVault.cpp Image.cpp miv.cpp Viewer.cpp Navigator.cpp
